#!/bin/bash
# gen_assert_bats.sh <out.bats> <log> <label>
#
# Turns a harness LAD log (see lib/asserts.js) into a bats file with one real
# @test per assertion. quickshell prefixes every console line with a colored
# "DEBUG qml:" tag, so both this generator and the generated tests match the
# LAD token unanchored and compare it as a line suffix. quickshell can also
# re-instantiate the config after Qt.quit() (a second onCompleted), so only
# the first run — up to the first LAD-SUMMARY line — is canonical. Each test
# addresses its own LAD line by index (sed -n Np), so duplicate assertion
# names match exactly and no engine re-run is needed; the bats pass is
# instant greps against the captured log. A missing LAD-SUMMARY (crash/
# timeout) or a run with zero assertions emits an explicit failing test.

set -u
out=$1 log=$2 label=$3
abs_log=$(cd "$(dirname "$log")" && pwd)/$(basename "$log")

first=$(sed '/LAD-SUMMARY/ q' "$log" 2>/dev/null) || first=""
has_summary=0
grep -q 'LAD-SUMMARY' "$log" 2>/dev/null && has_summary=1
n=$(printf '%s\n' "$first" | grep -cE 'LAD-(PASS|FAIL)') || n=0

{
  echo "# GENERATED by tests/lib/gen_assert_bats.sh from $(basename "$log"). Do not edit."
  printf 'LOG=%q\n' "$abs_log"
  i=0
  while IFS= read -r line; do
    rest=${line##*LAD-}
    set -- $rest
    name=$2
    i=$((i+1))
    cat <<EOF
@test "$label $name" {
  line=\$(sed '/LAD-SUMMARY/ q' "\$LOG" | grep -E 'LAD-(PASS|FAIL)' | sed -n ${i}p)
  want="LAD-PASS  $name"
  [[ \$line == *"\$want" ]] || { echo "got: \$line"; return 1; }
}

EOF
  done < <(printf '%s\n' "$first" | grep -E 'LAD-(PASS|FAIL)')
  if [ "$has_summary" -eq 0 ]; then
    cat <<EOF
@test "$label harness-completed" {
  echo "no LAD-SUMMARY in log — harness crashed or timed out"
  return 1
}

EOF
  elif [ "$n" -eq 0 ]; then
    cat <<EOF
@test "$label assertions-present" {
  echo "LAD-SUMMARY found but no LAD-PASS/LAD-FAIL assertion lines"
  return 1
}

EOF
  fi
} > "$out"
